site_name: Teaching Website

theme:
  name: material
  palette:
    primary: teal
  features:
    - navigation.tabs
    
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
